### ISSUE TITLE
Micropost_id no se está almacenando en solución

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#105]
Micropost_id no se está almacenando en solución

**Comment by pipevel** [comment]
Sera un problema de asociatividad?

**Comment by roadev** [comment]
Sí. Estoy en eso.

**Comment by roadev** [comment]
Como solución temporal, haré un formato para agregar manualmente el número del reto (ver ejemplo en staging).

**Comment by pipevel** [comment]
oka!

2015-07-31 14:49 GMT-05:00 Juan Roa <notifications@github.com>:

> Como solución temporal, haré un formato para agregar manualmente el número
> del reto (ver ejemplo en staging).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/eraazul/issues/105#issuecomment-126796029>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
Blog.lapapaya.org
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Actualmente almacenando manualmente. (Lo ingresa el usuario cuando crea la solución al reto).
