### ISSUE TITLE
Reparar merit y hacer que funcione en solutions

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#107]
Se está reparando merit desde 
https://github.com/roadev/lapapaya/commit/8eed70a65bacd3be24acd4b8766fa6ed24f0e9a7
Y volviendo a agregar las vistas y funcionalidades.

**Comment by roadev** [comment]
Funcionando perfectamente en staging y local

**Comment by roadev** [comment]
Merit reparado en todos los entornos.

**Comment by pipevel** [comment]
Oka!

2015-08-02 15:36 GMT-05:00 Juan Roa <notifications@github.com>:

> Merit reparado en todos los entornos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/107#issuecomment-127067883>
> .
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
Blog.lapapaya.org
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"
