### ISSUE TITLE
Levels & Points

### ISSUE THREAD

**Issue by pipevel** [pipevel/lapapaya.org#110]
La idea de momento es tener 3 niveles, aprendiz, empresario y maestro
El primer nivel sólo permitiría colaborar en otros proyectos y ayudar para aprender, el segundo podría permitir crear un negocio y tener colaboradores y el tercero permitiría mentorizar a otros proyectos. 
En el primer nivel se otorgan puntos por ayudar y colaborar en otros proyectos. 
Se otorgarían 5 puntos por cada proyecto que colabores, lo cual haría 15 puntos por colaborar en 3 proyectos o sueños, con esto te puedes hacer empresario. 
Adicionalmente se gana puntos permanentemente por cumplir retos.

**Comment by roadev** [comment]
Recuerda actualizar esto de ser necesario porfa :) @pipevel

**Comment by roadev** [comment]
Creo que esto más que badges es ranking...
Aprendiz
Empresario
Maestro

**Comment by pipevel** [comment]
Si, correcto, serían rankings. 
Podemos hacer todo por paquetes de 5 puntos, el primer nivel es cómplice, empezas ayudando a otros, después te harías soñador si querés sino segúis como cómplice y finalmente mentor. 
Me parece bien. 
Para registrar un sueño deberíamos pedir que la persona primero se haga cómplice, que opinas?

**Comment by roadev** [comment]
Correcto.
Podría ser!
Es como que de entrada hacer que la gente se comprometa con el sentido social de lapapaya y contribuya. Sería genial probar eso !

**Comment by roadev** [comment]
Estoy consignando todo esto en la wiki

**Comment by pipevel** [comment]
Listo,
Al pelo, me parece
Vi lo que hiciste ya con los puntos y el perfil de usuario,
Quedó muy bueno,
Deberíamos hacer ya lo del botón de cómplices,
Crear el scaffold y el formulario con una notificación al soñador cuando
alguien quiera apoyar su proyecto,
Viste la estructura del formulario de cómplice?

2015-09-10 22:12 GMT-05:00 Juan Roa <notifications@github.com>:

> Estoy consignando todo esto en la wiki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/110#issuecomment-139437887>
> .
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Estoy anotando lo del formulario.
Sí, es crear el modelo con scaffold y camellarle
Aunque hoy me la pasé fue mirando cómo crear el modelo de LaPapaya Academy y el diseño.

**Comment by pipevel** [comment]
Viste que dentro del videotutorial de Mauricio Duque explican como
comercializarlos?

2015-09-10 22:22 GMT-05:00 Juan Roa <notifications@github.com>:

> Estoy anotando lo del formulario.
> Sí, es crear el modelo con scaffold y camellarle
> Aunque hoy me la pasé fue mirando cómo crear el modelo de LaPapaya Academy
> y el diseño.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/110#issuecomment-139442463>
> .
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
@pipevel Lo que decías sobre cómpilce, soñador en los rakings...
Esos que propusiste ahora en los comentarios o estos que habías propuesto antes? 
Aprendiz
Empresario
Maestro
Porfa, necesito que en la wiki:
https://github.com/pipevel/lapapaya.org/wiki/Pol%C3%ADtica-de-puntos
Terminemos de consolidar esto con nombres propios.
Según eso, para subir del nivel 1 al 2 es con 3 colaboraciones en sueños.
El nivel cero, que es cuando sólo se registra el usuario, cómo le ponemos? usuario nuevo? o ?...

**Comment by roadev** [comment]
Esto ya está implementado actualmente.
