### ISSUE TITLE
No se suman puntos si falta username

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#112]
Actualmente, al ser username un campo obligatorio para el registro de un usuario, no suma puntos si el user no tiene su username.
Es decir, los antiguos users (obviamente no lo tienen porque es un campo nuevo), no pueden dar soluciones.
Se propone:
Dar un mensaje cuando se intente dar solución para que el usuario se dirija al userpanel y agregue un username.
Eliminar validación * (no se recomienda)

**Comment by pipevel** [comment]
Mmmm
Un poco grave..
Muchos se van a enredar,
Hagamos entonces la redirección para que creen un username.

El 2 de agosto de 2015, 15:36, Juan Roa <notifications@github.com> escribió:

> Actualmente, al ser username un campo obligatorio para el registro de un
> usuario, no suma puntos si el user no tiene su username.
> Es decir, los antiguos users (obviamente no lo tienen porque es un campo
> nuevo), no pueden dar soluciones.
> Se propone:
> Dar un mensaje cuando se intente dar solución para que el usuario se
> dirija al userpanel y agregue un username.
> Eliminar validación * (no se recomienda)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/112>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
Blog.lapapaya.org
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Por ahora la solución a eso es complicada...
Elegí ir por la segunda opción, no requerirlo pero sí hacer saber que es importante registrar el username y de hecho, agregarlo para los que no lo tienen.
Ahora funciona perfecto como está sea con username o no.
