### ISSUE TITLE
Integración de formulario de "ser cómplice"

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#125]
Actualmente el formulario existente se realiza por medio de un tercero.
Necesito que me expliques porfa cómo está funcionando esto actualmente... si te llega notificación.
La idea es que todo esto pueda saberlo el soñador al cuál otro usuario desea ayudarle o ser cómplice de su sueño y poder hacer contacto con aquel usuario.

@pipevel

**Comment by pipevel** [comment]
Hola Juan!
No, actualmente no llega la notificación y si claro, hay que crear el formulario dentro de las tablas de rails con la notificación para que sepas cuando alguien te quiere ayudar. 
De hecho he pensado que antes de que un usuario se haga soñador necesita primero haber ayudado algún sueño, así pedimos 5 puntos para que el usuario registre su sueño y primero haber ayudado a alguien. 
Que opinas?

**Comment by roadev** [comment]
Ok. Se creará entonces modelo para formulario de "ser cómplice"
Mañana cuadro un milestone para ello.

**Comment by pipevel** [comment]
ok!

2015-09-10 23:32 GMT-05:00 Juan Roa <notifications@github.com>:

> Ok. Se creará entonces modelo para formulario de "ser cómplice"
> Mañana cuadro un milestone para ello.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/125#issuecomment-139450231>
> .
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"
