### ISSUE TITLE
Creación del scaffold con formulario

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#126]

**Comment by roadev** [comment]
Creado, ahora se procede a darle estilo al formulario.

**Comment by pipevel** [comment]
Listo,
Dále!
Cómo te fué finalmente con la convocatoria?
Pudiste solucionar?

El 15 de septiembre de 2015, 14:39, Juan Roa <notifications@github.com>
escribió:

> Creado, ahora se procede a darle estilo al formulario.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/126#issuecomment-140514220>
> .
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"
