### ISSUE TITLE
Carta propiedad intelectual

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#127]
Confirmar si cumplimos los requerimientos sobre propiedad intelectual, y de no ser así, comenzar gestiones/averiguaciones.
De hecho considero esto muy importante independientemente de que apliquemos o no!

**Documento:**
https://appsco-raid2.s3.amazonaws.com/summoningfile/810b4eaa87b0436bac71916a081f147d/Anexo%205%20-%20Carta%20proteccion%20propiedad%20intelectual.pdf

**Comment by pipevel** [comment]
Listo!
Estoy en ello!
