### ISSUE TITLE
No se recalcula ranking cambiando las reglas

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#135]
Al cambiar las reglas del rank en rank_rules.rb de merit y corriendo las tareas de check_unprocessed y check_new_rules, los ranks que ya estaban asignados no se recalcular y en usuarios que no tenían nada asignado sí funcionan bien las nuevas reglas.

**Comment by pipevel** [comment]
No te entiendo bien,
Eso que traduce?
No están funcionando las rules?

El 21 de septiembre de 2015, 9:11, Juan Roa <notifications@github.com>
escribió:

> Al cambiar las reglas del rank en rank_rules.rb de merit y corriendo las
> tareas de check_unprocessed y check_new_rules, los ranks que ya estaban
> asignados no se recalcular y en usuarios que no tenían nada asignado sí
> funcionan bien las nuevas reglas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/135>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Sí funcionan pero si se cambian por x o y motivo, no se recalculan los ranks ya asignados con las nuevas reglas.
En la documentación vi el reset fue pero para badges y points, aún no hallo para ranks

**Comment by roadev** [comment]
Cierro issue debido a que se trabajará sin merit por ahora.
