### ISSUE TITLE
Crear reglas de niveles respecto a puntos obtenidos

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#137]
Crear reglas de niveles respecto a puntos obtenidos por ser cómplice.

**Comment by pipevel** [comment]
Listo men,
Hagale a eso, yo estoy presentando convocatoria Mintic, segunda fase de
premio ciudad cívica y convocatoria Museo la Tertulia, en lo que salga vos
estás en el equipo de trabajo!
También tenemos que postularnos a Start up chile!


2015-09-24 18:04 GMT-05:00 Juan Roa <notifications@github.com>:

> Crear reglas de niveles respecto a puntos obtenidos por ser cómplice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/137>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"
