### ISSUE TITLE
Colocar condicionales para crear sueño

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#154]
Actualmente se pueden crear sueños "vacíos " (sin nombre u otras variables)
Colocaré obligatorio el campo de sueño, al igual que los demás.

**Comment by pipevel** [comment]
Ok!

El 29 de octubre de 2015, 10:15, Juan Roa <notifications@github.com>
escribió:

> Actualmente se pueden crear sueños "vacíos " (sin nombre u otras variables)
> Colocaré obligatorio el campo de sueño, al igual que los demás.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/154>.
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Fixed with c702ddcdf2ba64fe44774d0b3132e8ea017fc150
