### ISSUE TITLE
Mostrar email de usuarios en Dreams profile

### ISSUE THREAD

**Issue by pipevel** [pipevel/lapapaya.org#170]

**Comment by roadev** [comment]
¿Deseas que se muestre el email en la vista show de los sueños? (es decir, en cada sueño)
@pipevel

**Comment by pipevel** [comment]
Si

2016-03-17 16:09 GMT-05:00 Juan Roa <notifications@github.com>:

> ¿Deseas que se muestre el email en la vista show de los sueños? (es decir,
> en cada sueño)
> @pipevel <https://github.com/pipevel>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/170#issuecomment-198083380>
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Trabajando en ello...

**Comment by roadev** [comment]
@pipevel revisate porfa.
Mira cualquier sueño y me dices cómo se ve...

**Comment by roadev** [comment]
Done with: https://github.com/pipevel/lapapaya.org/pull/171
