### ISSUE TITLE
Add user confirmation step for new users

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#172]

**Comment by roadev** [comment]
@pipevel 
Al implementar esto, ningún usuario podrá loguearse a menos que confirme su cuenta.
Es decir, es algo que no sólo afecta a los nuevos users (controlando que sean cuentas reales / confirmadas) sino que los antiguos users deben confirmar sus cuentas
Cuando se intenten loguear, el sistemas les arroja el mensaje y simplemente dan click en confirmar correo para que les llegue el email de activación.
¿Qué opinas?

Hecho parcialmente con: 8f662b9c49d580b3478a48cd2814189e4f5ec107, 05d120d2177a43a8e38ffb9ccd0840fa635e164d, 5a3e499f951d7bd43458598f679a93e4a2ac5fb1

**Comment by pipevel** [comment]
Hola Juan!
Me parece buenísimo!
De hecho te voy a pasar una DB con un montón de usuarios viejos para que importemos sus datos y les mandemos un correo con esto. 
Para que puedan volver a usar la plataforma!
:)
Hablamos esta semana que viene, 
Abrazo!

**Comment by roadev** [comment]
Vale @pipevel 
¿Hago deploy a producción?
Habría que notificar por lo menos a los usuarios de la db actual de heroku de lapapaya de la necesidad de confirmar su correo.

**Comment by pipevel** [comment]
Dale,
Hagamos deploy y enviemos la notificación.
Tenes los correos?

El 29 de marzo de 2016, 10:39, Juan Roa <notifications@github.com> escribió:

> Vale @pipevel <https://github.com/pipevel>
> ¿Hago deploy a producción?
> Habría que notificar por lo menos a los usuarios de la db actual de heroku
> de lapapaya de la necesidad de confirmar su correo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/172#issuecomment-202962867>
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
Como admin@lapapaya.org entra a:
http://lapapaya.org/adminpanel
Si quieres genero otra vista con los mails separados por comas mejor...

**Comment by roadev** [comment]
Deploy: Done
+2 points :)
https://github.com/pipevel/lapapaya.org/pull/174
