### ISSUE TITLE
Find alternative to Mandrill app

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#173]
Mandrill's email: final notice:

"The Mandrill team has chosen not to continue development of this add-on and decided to make a platform change that impacts both direct customers and Heroku customers."

Alternatives: MailGun (1000 emails per month -> free)
SendGrid

**Comment by pipevel** [comment]
Recibido!
Voy a hacer este issue!
:)

2016-03-24 14:43 GMT-05:00 Juan Roa <notifications@github.com>:

> Assigned #173 <https://github.com/pipevel/lapapaya.org/issues/173> to
> @pipevel <https://github.com/pipevel>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/173#event-602244791>
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by pipevel** [comment]
Mejor Mailgun, que opinas vos?

**Comment by pipevel** [comment]
Ya está instalado como add on, solo falta configurarlo. Para hacerlo habrá que desinstalar el Mailchimp, te parece si ponemos los pasos a seguir y los asignamos. No quiero empezar a hacer sin tener en cuenta lo que haya que hacer para desinstalar Mailchimp.

**Comment by roadev** [comment]
Igual el soporte de mailchimp ya murió... en este momento en teoría estamos sin emails.
Para la config de mailgun basta con agregar unos datos al environment de la app de lapapaya.
Desinstala el Mandrill, no hay problem.

**Comment by pipevel** [comment]
Oka!

El 25 de marzo de 2016, 11:15, Juan Roa <notifications@github.com> escribió:

> Igual el soporte de mailchimp ya murió... en este momento en teoría
> estamos sin emails.
> Para la config de mailgun basta con agregar unos datos al environment de
> la app de lapapaya.
> Desinstala el Mandrill, no hay problem.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/173#issuecomment-201347597>
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by pipevel** [comment]
Tienes el link de los datos de mailgun que hay que agregar a lapapaya para ponerlo a funcionar?
Ya te reenvío lo que me llegó hoy de mailchimp.

**Comment by roadev** [comment]
Using mailgun in production
Done with #179 + refactoring SMTP variables

**Comment by pipevel** [comment]
Excelente viejo Juan!
Te cuento que el proyecto de Jamundí y otros mas van avanzando.
Ya se realizó un trabajo de Diseño Gráfico que se pagó con moneda virtual.
De igual forma empezarán a haber otros mas con los que se aplicará el mismo
esquema.
Seguimos en contacto,
Te voy contando!

2016-04-06 10:47 GMT-05:00 Juan Roa <notifications@github.com>:

> Using mailgun in production
> Done with #179 <https://github.com/pipevel/lapapaya.org/pull/179> +
> refactoring SMTP variables
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/173#issuecomment-206436821>
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"

**Comment by roadev** [comment]
¿Con qué moneda virtual se pagó? @pipevel 
¡Vale!

**Comment by pipevel** [comment]
Con papayos!
;)

2016-04-06 13:02 GMT-05:00 Juan Roa <notifications@github.com>:

> ¿Con qué moneda virtual se pagó? @pipevel <https://github.com/pipevel>
> ¡Vale!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pipevel/lapapaya.org/issues/173#issuecomment-206491651>
>



-- 
Lapapaya.org

!Vitamina para tus sueños!
www.lapapaya.org

Felipe Velasquez Palacio
General Manager
Phone. 3207217643 / 3175658615
Cali - Colombia.

"Haciendo realidad los sueños de los innovadores sociales del Mundo Entero"
