### ISSUE TITLE
Revisar upgrade Lapapaya

### ISSUE THREAD

**Issue by pipevel** [pipevel/lapapaya.org#192]
Revisar el upgrade de lapapaya y mirar error que está saliendo en devise.

**Comment by roadev** [comment]
Porfa haz push en este repositorio para ver los cambios que hiciste y poder reproducir el error en local.
¿Hiciste rollback en producción? (heroku)

**Comment by roadev** [comment]
@pipevel si no tienes el remote del repositorio, haces esto en la consola, dentro del proyecto
`git remote add github https://github.com/pipevel/lapapaya.org.git`
y haces
`git push github master`
