### ISSUE TITLE
Hacer que Mandril de Mailchimp funcione

### ISSUE THREAD

**Issue by pipevel** [pipevel/lapapaya.org#82]
Poder hacer los remember my password y que funcione Mandril

**Comment by roadev** [comment]
¿Mandril para los mensajes por email del sistema (smtp)? Mandrill puede ser algo tedioso de configurar.
Existe uno llamado mailgun con mejores configuraciones y más apto para este tipo de apps web.

**Comment by pipevel** [comment]
Lo has implementado?
Ya intente con sendgrid y mandril y no he podido

**Comment by roadev** [comment]
Sí.
Lo he utilizado para servidores de node.js
Veré la app e intentaré implementarlo. Notificaré aquí el resultado.

**Comment by pipevel** [comment]
Oka

**Comment by roadev** [comment]
Mandrill ya funciona :)
