### ISSUE TITLE
Configuración de SMTP (correo) con mailgun

### ISSUE THREAD

**Issue by roadev** [pipevel/lapapaya.org#95]
Se realizará la configuración del SMTP para la app de LaPapaya con mailgun. Ya se verificó el dominio.
@pipevel La idea sería enviar emails automáticos cuando alguien se registre en la web con una bienvenida e invitación a la creación del sueño. ¿Te parece?
Pensaba en algo como un slider (no sé qué opines) para mostrar fotos de la comunidad/actividades de La Papaya (más adelante).

**Comment by pipevel** [comment]
Chevre!
Me parece vacano!

**Comment by roadev** [comment]
Ya se logró esta función con Mandrill.
Pregunta, vos pagás por Mandrill?
